Update readme with working example and update cli version to latest
dev-hanz-ops/install-gh-cli-action pull request #3
Opened 2023-07-19 14:40 UTC by frzkn

Currently, when used without a version, GitHub Action throws the following error.

Error:
Fix `uses` attribute must be a path, a Docker image, or owner/repo@ref error

2023-08-17 08:45 UTC, erikbrgn requested changes

2023-08-17 08:45 UTC, erikbrgn commented on README.md
> +  uses: dev-hanz-ops/install-gh-cli-action@0.1.0
```suggestion
  uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
```

2023-11-30 16:20 UTC, dev-hanz-ops commented on README.md
> -    gh-cli-version: 2.14.2 # optional, see action.yml for current default
please keep the comment. if you want, you can update the default in https://github.com/dev-hanz-ops/install-gh-cli-action/blob/master/action.yml#L8 and I'll release it as v0.1.1

2023-12-12 20:28 UTC, dev-hanz-ops approved these changes

2023-12-12 20:29 UTC, merged